[package]
name = "UMCG"
version = "0.1.0"
edition = "2021"

#[dependencies]
#num_cpus = "1.16.0"
[dependencies]
num_cpus = "1.16.0"
libc = "0.2.164"
rand = "0.9.0-beta.1"
crossbeam = "0.8.4"
parking_lot = "0.12.3"
