#[target.aarch64-unknown-linux-gnu]
#linker = "aarch64-unknown-linux-gnu-gcc"
#
#[target.aarch64-unknown-linux-musl]
#linker = "aarch64-unknown-linux-musl-gcc"
#
#[target.x86_64-unknown-linux-musl]
#linker = "x86_64-linux-musl-gcc"

